name: CustomItemLoader
version: 1.0-BETA
main: alvin0319\CustomItemLoader\CustomItemLoader
api: 4.0.0
authors: ["Redlive Studios", "alvin0319"]
extensions:
  Core: ">=8.0"
permissions:
  customitemloader.command.rsc:
    default: op
  customitemloader.command:
    default: op
